"""
Deterministic Eligibility Gate for Fix Agent V1/V2
Ensures patch generation is attempted ONLY for safe, localized, concrete findings:
- Verifier must have ACCEPTed the candidate
- Role must be correctness_logic or maintainability
- Single-file localization (rejects multi-file / cross-file / cross-cutting)
- Concrete/presence-type problem (rejects absence/missing checks)
- Source file is valid supported Java file (rejects generated/vendor/fixture/config files)
- Context is sufficient for localized fix
- Security findings are strictly NOT auto-fixed
"""

import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from verifier_prompt_builder import (
    classify_grounding_strategy,
    STRATEGY_ABSENCE_REFERENCE,
    STRATEGY_ABSENCE_RESOURCE_CLEANUP
)

# Roles eligible for automated patch generation in V1/V2
ELIGIBLE_ROLES = {"correctness_logic", "correctness", "maintainability"}

# Ineligible file path patterns (generated, vendor, test fixtures, configs)
INELIGIBLE_PATH_PATTERNS = [
    r"(^|/|\\)target(/|\\)",
    r"(^|/|\\)build(/|\\)",
    r"(^|/|\\)out(/|\\)",
    r"(^|/|\\)generated(/|\\)",
    r"(^|/|\\)generated-sources(/|\\)",
    r"(^|/|\\)proto(/|\\)",
    r"(^|/|\\)protobuf(/|\\)",
    r"(^|/|\\)antlr(/|\\)",
    r"(^|/|\\)grpc(/|\\)",
    r"(^|/|\\)thrift(/|\\)",
    r"(^|/|\\)codegen(/|\\)",
    r"(^|/|\\)node_modules(/|\\)",
    r"(^|/|\\)vendor(/|\\)",
    r"(^|/|\\)fixtures?(/|\\)",
    r"\.min\.",
    r"\.(xml|json|ya?ml|properties|md|txt|sh|bat|cmd|gradle|dockerfile)$",
]

# Absence indicators in problem description
ABSENCE_KEYWORDS = [
    "missing",
    "absence",
    "unclosed",
    "not closed",
    "not handled",
    "unhandled exception",
    "missing null check",
    "lacks error handling",
    "missing validation",
    "missing check",
    "no timeout",
    "missing synchronization",
]

# Security indicators that must not be auto-patched (using word boundaries for safety)
SECURITY_KEYWORD_PATTERNS = [
    r"\bsecurity\b",
    r"\bvulnerabilit(?:y|ies)\b",
    r"\bcve-\d+",
    r"\bsecret\b",
    r"\bpasswords?\b",
    r"\btokens?\b",
    r"\bapikeys?\b",
    r"\bapi_key\b",
    r"\bprivate_key\b",
    r"\binjections?\b",
    r"\bxss\b",
    r"\bcsrf\b",
    r"\bdeserialization\b",
    r"\bprivilege escalation\b",
    r"\brce\b",
    r"\bssrf\b",
    r"\bauth(?:entication|orization)?\b",
    r"\bcredentials?\b",
    r"\bhardcoded\b",
]

# High-confidence generated source header patterns
GENERATED_HEADER_PATTERNS = [
    r"//\s*generated by\b",
    r"/\*\s*generated by\b",
    r"//\s*generated from\b",
    r"@(?:javax\.annotation\.|jakarta\.annotation\.)?Generated\b",
    r"//\s*Generated by the protocol buffer compiler",
    r"//\s*Generated from .* by ANTLR",
    r"\bDO NOT EDIT\b",
]


def is_security_finding(finding: Dict[str, Any]) -> bool:
    """Checks whether the finding is a security issue."""
    role = str(finding.get("source_reviewer", "")).strip().lower()
    if "security" in role:
        return True

    problem = str(finding.get("problem", "")).lower()
    category = str(finding.get("category", "")).lower()
    rule = str(finding.get("rule", "")).lower()

    combined = f"{problem} {category} {rule}"
    for pat in SECURITY_KEYWORD_PATTERNS:
        if re.search(pat, combined, re.IGNORECASE):
            return True
    return False


def is_absence_type_finding(finding: Dict[str, Any]) -> bool:
    """Checks whether the finding describes an absence/missing code issue."""
    problem = str(finding.get("problem", "")).strip()
    prob_lower = problem.lower()
    
    # 1. Verifier Grounding Strategy check for resource cleanups
    strategy = classify_grounding_strategy(problem)
    if strategy == STRATEGY_ABSENCE_RESOURCE_CLEANUP:
        return True

    # 2. Localized presence maintainability issues (unused variables, dead assignments, redundant logic, operator precedence)
    # are concrete statement removals/edits and must not be rejected as absence issues.
    presence_exemptions = (
        "unused local variable",
        "unused variable",
        "unused local",
        "unused stringbuilder",
        "dead assignment",
        "redundant boolean",
        "redundant double negation",
        "redundant negation",
        "operator precedence",
        "arithmetic precedence",
        "missing parentheses",
        "missing grouping",
        "parentheses",
        "grouping"
    )
    if any(k in prob_lower for k in presence_exemptions):
        return False

    # 3. Problem keyword heuristics for true missing code / absence
    for kw in ABSENCE_KEYWORDS:
        if kw in prob_lower:
            return True

    return False


def is_valid_source_file(file_path: str, file_content: Optional[str] = None) -> bool:
    """Verifies that the target file is a supported source file and not generated/vendor/fixture."""
    if not file_path or not isinstance(file_path, str):
        return False

    norm_path = file_path.replace("\\", "/")
    
    # Must be a Java file in V1/V2
    if not norm_path.lower().endswith(".java"):
        return False

    # Check against ineligible path patterns
    for pattern in INELIGIBLE_PATH_PATTERNS:
        if re.search(pattern, norm_path, re.IGNORECASE):
            return False

    # Check file content header for generated code markers
    if file_content:
        header_sample = file_content[:1500]
        for pat in GENERATED_HEADER_PATTERNS:
            if re.search(pat, header_sample, re.IGNORECASE):
                return False

    return True


def check_fix_eligibility(
    finding: Dict[str, Any],
    file_content: Optional[str] = None,
    diff_hunks: Optional[List[Dict[str, Any]]] = None
) -> Dict[str, Any]:
    """
    Evaluates finding eligibility deterministically against V1/V2 safety rules.
    Returns:
        {
            "eligible": bool,
            "reason": str
        }
    """
    # 1. Verifier Decision Gate
    decision = str(finding.get("decision", "")).strip().upper()
    if decision and decision != "ACCEPT":
        return {
            "eligible": False,
            "reason": "unverified_or_rejected_finding"
        }

    # 2. Structured Finding Type / Scope Gate (Multi-File & Generated Source Checks)
    finding_type = str(finding.get("finding_type") or "").strip().lower()
    context_scope = str(finding.get("context_scope") or "").strip().lower()
    scope = str(finding.get("scope") or "").strip().lower()

    if finding_type in ("generated_source", "generated", "vendor") or context_scope in ("generated_source_rule", "generated_rule", "vendor_rule") or finding.get("is_generated") or finding.get("is_vendor"):
        return {
            "eligible": False,
            "reason": "unsupported_file_type"
        }

    if finding_type in ("multi_file", "cross_file", "cross_cutting") or context_scope in ("multi_file", "cross_file", "cross_cutting", "multi_file_rule", "cross_file_rule") or scope in ("multi_file", "cross_file", "cross_cutting", "project_wide"):
        return {
            "eligible": False,
            "reason": "multi_file_not_supported"
        }

    if int(finding.get("file_count") or 1) > 1 or len(finding.get("affected_files") or []) > 1 or len(finding.get("related_files") or []) > 0 or finding.get("is_multi_file") or finding.get("cross_file"):
        return {
            "eligible": False,
            "reason": "multi_file_not_supported"
        }

    # 3. File Path & Type Gate (must be valid Java source and not generated/vendor)
    file_path = finding.get("file") or finding.get("file_path") or ""
    effective_content = file_content or finding.get("after_source") or ""
    if not is_valid_source_file(file_path, file_content=effective_content):
        return {
            "eligible": False,
            "reason": "unsupported_file_type"
        }

    # 4. Security Gate
    if is_security_finding(finding):
        return {
            "eligible": False,
            "reason": "security_findings_not_auto_fixed"
        }

    # 5. Role/Category Gate
    role = str(finding.get("source_reviewer", "")).strip().lower()
    if role not in ELIGIBLE_ROLES:
        return {
            "eligible": False,
            "reason": f"role_{role}_not_supported_for_auto_fix"
        }

    # 6. Absence-Type Gate
    if is_absence_type_finding(finding):
        return {
            "eligible": False,
            "reason": "absence_type_not_auto_fixed"
        }

    # 7. Multi-File / Cross-File Conservative Text Fallback
    problem_text = str(finding.get("problem", "")).lower()
    multi_file_terms = (
        "across files", "multiple files", "cross-file", "cross file",
        "other file", "different file", "another file", "multiple classes",
        "across classes", "across service", "across package", "migration script"
    )
    if any(term in problem_text for term in multi_file_terms):
        return {
            "eligible": False,
            "reason": "multi_file_not_supported"
        }

    # 8. Context Sufficiency Gate
    after_source = finding.get("after_source") or file_content or ""
    code_snippet = finding.get("code_snippet") or ""
    if not after_source and not code_snippet and not diff_hunks:
        return {
            "eligible": False,
            "reason": "insufficient_context"
        }

    # 9. Expected Change Size Gate (V1 max 20 lines)
    if "refactor entire class" in problem_text or "rewrite module" in problem_text:
        return {
            "eligible": False,
            "reason": "expected_patch_too_large"
        }

    return {
        "eligible": True,
        "reason": "eligible_for_fix"
    }

