"""
GitHub REST API Client for Pull Request Review Comments
Handles:
- Listing PR comments
- Creating or updating bot summary comments with marker <!-- pr-review-agent -->
- Markdown formatting for AI PR review findings (with role/severity emojis)
- Safe error handling and token privacy
"""

import json
import logging
import os
import urllib.error
import urllib.request
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("github_client")

BOT_COMMENT_MARKER = "<!-- pr-review-agent -->"

ROLE_EMOJIS = {
    "security_validation": "🔴",
    "security": "🔴",
    "correctness_logic": "🟠",
    "correctness": "🟠",
    "maintainability": "🟡",
}

SEVERITY_EMOJIS = {
    "critical": "🔴",
    "high": "🔴",
    "medium": "🟠",
    "low": "🔵",
}


def get_emoji_for_finding(finding: Dict[str, Any]) -> str:
    """Selects appropriate emoji based on severity or reviewer role."""
    sev = str(finding.get("severity", "")).lower().strip()
    if sev in SEVERITY_EMOJIS:
        return SEVERITY_EMOJIS[sev]

    role = str(finding.get("source_reviewer", "")).lower().strip()
    if role in ROLE_EMOJIS:
        return ROLE_EMOJIS[role]

    return "⚠️"


def get_role_display_name(role: str) -> str:
    """Formats reviewer role into human-readable label."""
    mapping = {
        "security_validation": "Security",
        "correctness_logic": "Correctness & Logic",
        "maintainability": "Maintainability",
    }
    return mapping.get(role.lower().strip(), role.replace("_", " ").title())


def format_review_summary_markdown(
    head_sha: str,
    verified_findings: List[Dict[str, Any]],
    rejected_findings: List[Dict[str, Any]],
    summary_stats: Optional[Dict[str, Any]] = None
) -> str:
    """
    Generates structured, user-friendly Markdown containing the review summary.
    Includes the hidden marker <!-- pr-review-agent --> at the beginning.
    """
    short_sha = head_sha[:7] if head_sha else "unknown"
    verified_count = len(verified_findings)
    rejected_count = len(rejected_findings)

    lines = [
        BOT_COMMENT_MARKER,
        "",
        "## 🤖 AI PR Review",
        "",
        f"**Reviewed commit:** `{short_sha}`",
        "",
        "### Summary",
        f"- Verified findings: **{verified_count}**",
        f"- Rejected findings: **{rejected_count}**",
        ""
    ]

    if verified_count == 0:
        lines.append("✅ **No verified issues found.**")
        lines.append("")
    else:
        lines.append("### Findings")
        lines.append("")

        for idx, finding in enumerate(verified_findings, start=1):
            role_key = finding.get("source_reviewer", "General")
            role_name = get_role_display_name(role_key)
            emoji = get_emoji_for_finding(finding)

            file_path = finding.get("file", "Unknown file")
            line_no = finding.get("line")
            loc_str = f"{file_path}:{line_no}" if line_no is not None else file_path

            problem_text = finding.get("problem", "No problem description provided.")
            reason_text = finding.get("verifier_reason") or finding.get("failure_scenario") or finding.get("verifier_evidence")
            suggested_fix = finding.get("suggested_fix")

            lines.append(f"#### {emoji} {role_name} — `{loc_str}`")
            lines.append(f"**Problem:** {problem_text}")
            lines.append("")

            if reason_text:
                lines.append(f"**Reason:** {reason_text}")
                lines.append("")

            if suggested_fix:
                lines.append(f"**Suggested Fix:** `{suggested_fix}`" if "\n" not in suggested_fix else f"**Suggested Fix:**\n```java\n{suggested_fix}\n```")
                lines.append("")

            if idx < verified_count:
                lines.append("---")
                lines.append("")

    lines.append("---")
    lines.append("*Generated by PR Review Agent.*")
    return "\n".join(lines)


class GitHubClient:
    def __init__(self, token: Optional[str] = None, api_base: str = "https://api.github.com"):
        self.token = token or os.getenv("GITHUB_TOKEN")
        self.api_base = api_base.rstrip("/")

    def _get_headers(self) -> Dict[str, str]:
        headers = {
            "Accept": "application/vnd.github+json",
            "User-Agent": "PR-Review-Agent",
            "Content-Type": "application/json"
        }
        if self.token:
            headers["Authorization"] = f"Bearer {self.token}"
        return headers

    def _send_request(self, method: str, url: str, payload: Optional[Dict[str, Any]] = None) -> Tuple[int, Any]:
        """Performs HTTP request to GitHub API using standard urllib."""
        data_bytes = json.dumps(payload).encode("utf-8") if payload is not None else None
        req = urllib.request.Request(url, data=data_bytes, headers=self._get_headers(), method=method)

        try:
            with urllib.request.urlopen(req) as response:
                status_code = response.getcode()
                raw = response.read().decode("utf-8")
                resp_data = json.loads(raw) if raw else {}
                return status_code, resp_data
        except urllib.error.HTTPError as e:
            raw_err = e.read().decode("utf-8")
            logger.warning(f"GitHub API {method} {url} returned HTTP {e.code}: {raw_err}")
            return e.code, raw_err
        except Exception as e:
            logger.warning(f"GitHub API {method} {url} network error: {e}")
            raise

    def list_pr_comments(self, repo_full_name: str, pr_number: int) -> List[Dict[str, Any]]:
        """Fetches issue comments for the specified PR."""
        url = f"{self.api_base}/repos/{repo_full_name}/issues/{pr_number}/comments"
        status_code, data = self._send_request("GET", url)
        if status_code == 200 and isinstance(data, list):
            return data
        return []

    def find_agent_comment(self, repo_full_name: str, pr_number: int) -> Optional[Dict[str, Any]]:
        """Searches existing comments for the unique bot comment marker."""
        comments = self.list_pr_comments(repo_full_name, pr_number)
        for comment in comments:
            body = comment.get("body", "")
            if BOT_COMMENT_MARKER in body:
                return comment
        return None

    def create_comment(self, repo_full_name: str, pr_number: int, body: str) -> Dict[str, Any]:
        """Creates a new comment on the PR."""
        url = f"{self.api_base}/repos/{repo_full_name}/issues/{pr_number}/comments"
        status_code, data = self._send_request("POST", url, payload={"body": body})
        if status_code not in (200, 201):
            raise RuntimeError(f"Failed to create GitHub comment (HTTP {status_code})")
        return data

    def update_comment(self, repo_full_name: str, comment_id: int, body: str) -> Dict[str, Any]:
        """Updates an existing comment on the PR."""
        url = f"{self.api_base}/repos/{repo_full_name}/issues/comments/{comment_id}"
        status_code, data = self._send_request("PATCH", url, payload={"body": body})
        if status_code not in (200, 201):
            raise RuntimeError(f"Failed to update GitHub comment {comment_id} (HTTP {status_code})")
        return data

    def publish_review_summary(
        self,
        repo_full_name: str,
        pr_number: int,
        head_sha: str,
        verified_findings: List[Dict[str, Any]],
        rejected_findings: List[Dict[str, Any]],
        summary_stats: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Idempotently publishes or updates the single PR review summary comment on GitHub.
        """
        if not self.token:
            logger.warning("GITHUB_TOKEN is not configured. Skipping GitHub comment publishing.")
            return {"status": "skipped", "reason": "GITHUB_TOKEN not configured"}

        body_markdown = format_review_summary_markdown(
            head_sha=head_sha,
            verified_findings=verified_findings,
            rejected_findings=rejected_findings,
            summary_stats=summary_stats
        )

        existing_comment = self.find_agent_comment(repo_full_name, pr_number)
        if existing_comment and "id" in existing_comment:
            comment_id = existing_comment["id"]
            logger.info(f"Updating existing PR Review Agent comment #{comment_id} on {repo_full_name}#{pr_number}")
            self.update_comment(repo_full_name, comment_id, body_markdown)
            return {"status": "updated", "comment_id": comment_id}
        else:
            logger.info(f"Creating new PR Review Agent comment on {repo_full_name}#{pr_number}")
            res = self.create_comment(repo_full_name, pr_number, body_markdown)
            comment_id = res.get("id")
            return {"status": "created", "comment_id": comment_id}
